### ISSUE TITLE
Issue-1-Home Page

### ISSUE THREAD

**Issue by GustavoAyala1** [GustavoAyala1/final-project-Gustavo-Ayala#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the most popular/ newest places on home page
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can search for places of interest / places they would like to visit and see what is there. They can save locations to a favorites section and leave comments to help others judge the area. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![figma-home](https://user-images.githubusercontent.com/80282083/147501835-b7c0da02-c068-48f5-9be9-5ee0750b1a67.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create root div
- [x] Create nav div with search input form
- [ ] carrousel with popular locations
- [x] create side bars with random saved images
- [x] create favorites tab at bottom

### 🐘 Database

- [ ] Update `schema.sql` to add the tables and connect them correctly
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
