### ISSUE TITLE
Issue-2-Search functions

### ISSUE THREAD

**Issue by GustavoAyala1** [GustavoAyala1/final-project-Gustavo-Ayala#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for location and main location takes up the top spot while sub locations populate lower areads
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User searches for country/state/city and the country/state/city picture takes up top spot with a description if available while cities / activities / attractions / comments take lower spots. If there are comments they are also displayed / if not then just a button with add comments is displayed
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![figma-search](https://user-images.githubusercontent.com/80282083/147505291-af2ab9e3-1083-47f7-a988-ef0d7ae644e1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] Search functionality is available
         - [ ] you can search only for country
         - [ ] if adding state then country is required
         - [ ] if adding city state and country are required
         - [ ] MIGHT be able to just have one search input - will try
- [ ] search automatically fills in main picture / description with what is found
- [ ] if multiple pictures then a carrousel of main pictures
- [ ] button on main picture to save location

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
